# Generated by Django 4.2.2 on 2023-07-29 16:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/author/user_2.jpg', upload_to='post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7bfd6f9f-900f-40bf-9371-2b901ac80852'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
