# Generated by Django 4.2.2 on 2023-07-29 20:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('73f95f6e-9966-49b6-b6e6-6f35166a235a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
