# Generated by Django 4.2.2 on 2023-07-29 20:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dab7c9f1-866f-4d72-9acc-0345c0fedf0a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
