# Generated by Django 4.2.2 on 2023-07-07 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='preferences',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='preferences',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='core.preference'),
        ),
    ]
