# Generated by Django 4.2.2 on 2023-07-13 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_enquiry_preferences_enquiry_preferences'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={'verbose_name': 'Enquiries'},
        ),
    ]
